Repository DFY-NCSU/CoinCanvas, pull requests merged in 2024-11, with the labels that each got.

#2 Initialize the standard file structure
  backend/.env
  backend/app/__init__.py
  backend/app/crud.py
  backend/app/database.py
  backend/app/main.py
  backend/app/models.py
  backend/app/routers/__init__.py
  backend/app/routers/expenses.py
  backend/app/routers/users.py
  backend/app/schemas.py
  backend/requirements.txt
  backend/tests/__init__.py
  backend/tests/test_api.py
  docker-compose.yml
  frontend/lib/main.dart
  frontend/pubspec.yaml
Labels: documentation

#4 Update backend implementation and finish the simple testing.
  backend/.env
  backend/DockerFile
  backend/app/__pycache__/__init__.cpython-310.pyc
  backend/app/__pycache__/crud.cpython-310.pyc
  backend/app/__pycache__/database.cpython-310.pyc
  backend/app/__pycache__/main.cpython-310.pyc
  backend/app/__pycache__/models.cpython-310.pyc
  backend/app/__pycache__/schemas.cpython-310.pyc
  backend/app/crud.py
  backend/app/database.py
  backend/app/main.py
  backend/app/models.py
  backend/app/routers/expenses.py
  backend/app/routers/users.py
  backend/app/schemas.py
  backend/expenses.db
  backend/requirements.txt
  backend/tests/test_api.py
  docker-compose.yml
  frontend/DockerFile
  frontend/lib/main.dart
  frontend/lib/models/expense.dart
  frontend/lib/screens/add_expense_screen.dart
  frontend/lib/screens/home_screen.dart
  frontend/lib/screens/statistics_screen.dart
  frontend/lib/services/api_service.dart
  frontend/lib/utils/constants.dart
  frontend/lib/widgets/expense_card.dart
  frontend/lib/widgets/expense_form.dart
  frontend/nginx.conf
  frontend/pubspec.yaml
Labels: enhancement

#7 feat: add .gitignore and clean up ignored files
  .gitignore
  backend/.env
  backend/app/__pycache__/__init__.cpython-310.pyc
  backend/app/__pycache__/crud.cpython-310.pyc
  backend/app/__pycache__/database.cpython-310.pyc
  backend/app/__pycache__/main.cpython-310.pyc
  backend/app/__pycache__/models.cpython-310.pyc
  backend/app/__pycache__/schemas.cpython-310.pyc
  backend/expenses.db
Labels: enhancement

#9 add dependency for email_validator
  backend/requirements.txt
Labels: bug

#11 add test cases for backend api
  backend/tests/test_api_create_expenses.py
  backend/tests/test_api_delete_expenses.py
  backend/tests/test_api_login.py
  backend/tests/test_api_read_expenses.py
  backend/tests/test_api_register.py
Labels: enhancement

#14 Add logo pictures
  README.md
  assets/intro.jpg
  assets/logo.png
Labels: enhancement

#15 add dependencies for backend testing
  backend/requirements.txt
Labels: bug

#16 Add workflows
  .github/workflows/flake8.yml
  .github/workflows/style.yml
  .github/workflows/syntax.yml
  .github/workflows/test_backend.yml
  README.md
  backend/tests/_test_api.py
Labels: enhancement

#18 format code based on flake8
  README.md
  backend/app/crud.py
  backend/app/database.py
  backend/app/main.py
  backend/app/models.py
  backend/app/routers/expenses.py
  backend/app/routers/users.py
  backend/app/schemas.py
  backend/tests/test_api.py.bak
  backend/tests/test_api_create_expenses.py
  backend/tests/test_api_delete_expenses.py
  backend/tests/test_api_login.py
  backend/tests/test_api_read_expenses.py
  backend/tests/test_api_register.py
Labels: enhancement

#19 fix logical bugs in backend
  backend/app/crud.py
  backend/app/schemas.py
Labels: bug

#28 Fix bug in data statistics and dark mode
  frontend/lib/screens/add_expense_screen.dart
  frontend/lib/screens/statistics_screen.dart
Labels: bug

#29 add test cases for group function in backend
  backend/app/crud.py
  backend/tests/test_api_create_group_expenses.py
  backend/tests/test_api_delete_group_expenses.py
  backend/tests/test_api_group.py
  backend/tests/test_api_read_group_expenses.py
Labels: bug, enhancement, support

#36 Fix bug in code coverage calculation
  .github/workflows/test_backend.yml
  .gitignore
  backend/app/routers/__init__.py
  backend/app/routers/expenses.py
  backend/app/routers/users.py
  backend/requirements.txt
  backend/tests/test_api_create_expenses.py
  backend/tests/test_api_create_group_expenses.py
  backend/tests/test_api_delete_expenses.py
  backend/tests/test_api_delete_group_expenses.py
  backend/tests/test_api_group.py
  backend/tests/test_api_login.py
  backend/tests/test_api_read_expenses.py
  backend/tests/test_api_read_group_expenses.py
  backend/tests/test_api_register.py
Labels: bug

#37 Add frontend tests
  frontend/test/unit/models/expense_test.dart
  frontend/test/widget_test.dart
Labels: enhancement, support

#41 Extra test case for the login
  backend/tests/test_api_login.py
  backend/tests/test_api_read_expenses.py
Labels: support

#44 Add some docs
  CONTRIBUTING.md
  Code_Of_Conduct.md
  INSTALL.md
  LICENSE.md
  README.md
  docs/CodeDescription.md
  docs/CoinCanvas.md
  docs/MiniTutorial.md
Labels: enhancement

#45 Ai support
  frontend/lib/config/api_config.dart
  frontend/lib/extensions/iterable_extensions.dart
  frontend/lib/screens/statistics_screen.dart
  frontend/lib/widgets/ai_chat_widget.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: enhancement, support

#46 Add future map in the README
  README.md
Labels: documentation

#48 Add support for group in frontend
  backend/app/crud.py
  backend/app/main.py
  backend/app/models.py
  backend/app/schemas.py
  frontend/lib/models/group.dart
  frontend/lib/models/group_expense.dart
  frontend/lib/models/group_member.dart
  frontend/lib/screens/add_group_expense_screen.dart
  frontend/lib/screens/create_group_screen.dart
  frontend/lib/screens/group_detail_screen.dart
  frontend/lib/screens/group_list_screen.dart
  frontend/lib/screens/home_screen.dart
  frontend/lib/screens/join_group_screen.dart
  frontend/lib/services/api_service.dart
  frontend/lib/utils/string_utils.dart
  frontend/lib/widgets/custom_split_form.dart
Labels: enhancement, support
